apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "transmission.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "transmission.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "transmission.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.environment }}
          env:
            {{- range $key,$val := .Values.environment}}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /transmission/web/
              port: http
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /transmission/web/
              port: http
            initialDelaySeconds: 15
          {{- with .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if or .Values.persistence.enabled .Values.persistence.nfs.enabled }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: {{ template "transmission.fullname" . }}
              mountPath: /config
            {{- end }}
            {{- if .Values.persistence.nfs.enabled }}
            {{- range .Values.persistence.nfs.mounts}}
            - name: {{ .mountName }}
              mountPath: {{ .destinationPath }}
            {{- end }}
            {{- end }}
          {{- end }}
      {{- if or .Values.persistence.enabled .Values.persistence.nfs.enabled }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: {{ template "transmission.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ template "transmission.fullname" . }}-pvc
        {{- end }}
        {{- if .Values.persistence.nfs.enabled }}
        {{- range .Values.persistence.nfs.mounts }}
        - name: {{ .mountName }}
          persistentVolumeClaim:
            {{- if .existingClaim }}
            claimName: {{ .existingClaim }}
            {{ else }}
            claimName: {{ .mountName }}-pvc
            {{- end }}
        {{- end }}
        {{- end }}
      {{- end }} 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
